### ISSUE TITLE
Using Capsule with Spark yields ConcurrentModificationException on terminating the application

### ISSUE THREAD

**Issue by omarzouk** [puniverse/capsule#132]
Hi! I'm attempting to use Capsule as a FatJar for an apache spark application. Capsule is AMAZING btw! I was lost to 9 circles of dependency hell before I found this!

So, everything works fine up until the end, then the job fails due to a `ConcurrentModificationException` exception being thrown by capsule during cleanup.

I understand this might be by design and it seems yarn deletes some folders [line 32 in code] that might be causing this. If this is in fact hard to fix, is there a flag I can use to skip the cleanup? My use-case requires that I teardown the cluster anyway after the job finishes, so cleanup is not really needed.

Thanks!

```
AM Container for appattempt_1549311784724_0016_000001 exited with exitCode: 13
Failing this attempt.Diagnostics: [2019-02-05 00:36:19.426]Exception from container-launch.
Container id: container_1549311784724_0016_01_000001
Exit code: 13
[2019-02-05 00:36:19.427]Container exited with a non-zero exit code 13. Error file: prelaunch.err.
Last 4096 bytes of prelaunch.err :
Last 4096 bytes of stderr :
ster$$anonfun$run$1.apply(ApplicationMaster.scala:245)
at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$3.run(ApplicationMaster.scala:773)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.Subject.doAs(Subject.java:422)
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1893)
at org.apache.spark.deploy.yarn.ApplicationMaster.doAsUser(ApplicationMaster.scala:772)
at org.apache.spark.deploy.yarn.ApplicationMaster.run(ApplicationMaster.scala:244)
at org.apache.spark.deploy.yarn.ApplicationMaster$.main(ApplicationMaster.scala:797)
at org.apache.spark.deploy.yarn.ApplicationMaster.main(ApplicationMaster.scala)
CAPSULE: Cleanup
CAPSULE: Cleanup
[Thread-3] INFO org.apache.spark.SparkContext - Invoking stop() from shutdown hook
[Thread-3] INFO org.spark_project.jetty.server.AbstractConnector - Stopped Spark@54941dfd{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}
[Thread-3] INFO org.apache.spark.ui.SparkUI - Stopped Spark web UI at http://content-w-0.c.syb-staging-content.internal:4040
[pool-1-thread-1] INFO org.apache.spark.scheduler.DAGScheduler - Job 18 failed: foreach at BoundedDataset.java:117, took 2.597691 s
[Thread-3] INFO org.apache.spark.scheduler.DAGScheduler - ResultStage 24 (foreach at BoundedDataset.java:117) failed in 2.523 s due to Stage cancelled because SparkContext was shut down
[ForkJoinPool-1-worker-5] INFO org.apache.spark.SparkContext - SparkContext already stopped.
[dispatcher-event-loop-0] INFO org.apache.spark.MapOutputTrackerMasterEndpoint - MapOutputTrackerMasterEndpoint stopped!
[Thread-3] INFO org.apache.spark.storage.memory.MemoryStore - MemoryStore cleared
[Thread-3] INFO org.apache.spark.storage.BlockManager - BlockManager stopped
[Thread-3] INFO org.apache.spark.storage.BlockManagerMaster - BlockManagerMaster stopped
[dispatcher-event-loop-0] INFO org.apache.spark.scheduler.OutputCommitCoordinator$OutputCommitCoordinatorEndpoint - OutputCommitCoordinator stopped!
[Thread-3] INFO org.apache.spark.SparkContext - Successfully stopped SparkContext
[Thread-3] INFO org.apache.spark.util.ShutdownHookManager - Shutdown hook called
[Thread-3] INFO org.apache.spark.util.ShutdownHookManager - Deleting directory /hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1549311784724_0016/spark-7fcba0a0-cff9-4cbd-b6fc-71c3f8acdc9b
CAPSULE EXCEPTION: nullCAPSULE: /var/lib/hadoop-yarn/.capsule/apps/content-provider-pipeline_0.1.0-SNAPSHOT/.lock
while processing null null: null
CAPSULE: Exception on thread cleanup: null
CAPSULE EXCEPTION: null while processing null null: null
java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
at java.util.ArrayList$Itr.next(ArrayList.java:859)
at Capsule.cleanup0(Capsule.java:1428)
at Capsule.cleanup(Capsule.java:1414)
at Capsule.cleanup1(Capsule.java:1401)
at Capsule.run(Capsule.java:1319)
at java.lang.Thread.run(Thread.java:748)
java.lang.InterruptedException
at java.lang.Object.wait(Native Method)
at java.lang.Object.wait(Object.java:502)
at java.lang.UNIXProcess.waitFor(UNIXProcess.java:395)
at Capsule.launch0(Capsule.java:1382)
at Capsule.launch(Capsule.java:1351)
at Capsule.launch(Capsule.java:1280)
at Capsule.main0(Capsule.java:399)
at Capsule.main(Capsule.java:379)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:678)
Exception in thread "cleanup" java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
at java.util.ArrayList$Itr.next(ArrayList.java:859)
at Capsule.cleanup0(Capsule.java:1428)
at Capsule.cleanup(Capsule.java:1414)
at Capsule.cleanup1(Capsule.java:1401)
at Capsule.run(Capsule.java:1319)
at java.lang.Thread.run(Thread.java:748)
[2019-02-05 00:36:19.428]Container exited with a non-zero exit code 13. Error file: prelaunch.err.
Last 4096 bytes of prelaunch.err :
Last 4096 bytes of stderr :
ster$$anonfun$run$1.apply(ApplicationMaster.scala:245)
at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$3.run(ApplicationMaster.scala:773)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.Subject.doAs(Subject.java:422)
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1893)
at org.apache.spark.deploy.yarn.ApplicationMaster.doAsUser(ApplicationMaster.scala:772)
at org.apache.spark.deploy.yarn.ApplicationMaster.run(ApplicationMaster.scala:244)
at org.apache.spark.deploy.yarn.ApplicationMaster$.main(ApplicationMaster.scala:797)
at org.apache.spark.deploy.yarn.ApplicationMaster.main(ApplicationMaster.scala)
CAPSULE: Cleanup
CAPSULE: Cleanup
[Thread-3] INFO org.apache.spark.SparkContext - Invoking stop() from shutdown hook
[Thread-3] INFO org.spark_project.jetty.server.AbstractConnector - Stopped Spark@54941dfd{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}
[Thread-3] INFO org.apache.spark.ui.SparkUI - Stopped Spark web UI at http://content-w-0.c.syb-staging-content.internal:4040
[pool-1-thread-1] INFO org.apache.spark.scheduler.DAGScheduler - Job 18 failed: foreach at BoundedDataset.java:117, took 2.597691 s
[Thread-3] INFO org.apache.spark.scheduler.DAGScheduler - ResultStage 24 (foreach at BoundedDataset.java:117) failed in 2.523 s due to Stage cancelled because SparkContext was shut down
[ForkJoinPool-1-worker-5] INFO org.apache.spark.SparkContext - SparkContext already stopped.
[dispatcher-event-loop-0] INFO org.apache.spark.MapOutputTrackerMasterEndpoint - MapOutputTrackerMasterEndpoint stopped!
[Thread-3] INFO org.apache.spark.storage.memory.MemoryStore - MemoryStore cleared
[Thread-3] INFO org.apache.spark.storage.BlockManager - BlockManager stopped
[Thread-3] INFO org.apache.spark.storage.BlockManagerMaster - BlockManagerMaster stopped
[dispatcher-event-loop-0] INFO org.apache.spark.scheduler.OutputCommitCoordinator$OutputCommitCoordinatorEndpoint - OutputCommitCoordinator stopped!
[Thread-3] INFO org.apache.spark.SparkContext - Successfully stopped SparkContext
[Thread-3] INFO org.apache.spark.util.ShutdownHookManager - Shutdown hook called
[Thread-3] INFO org.apache.spark.util.ShutdownHookManager - Deleting directory /hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1549311784724_0016/spark-7fcba0a0-cff9-4cbd-b6fc-71c3f8acdc9b
CAPSULE EXCEPTION: nullCAPSULE: /var/lib/hadoop-yarn/.capsule/apps/content-provider-pipeline_0.1.0-SNAPSHOT/.lock
while processing null null: null
CAPSULE: Exception on thread cleanup: null
CAPSULE EXCEPTION: null while processing null null: null
java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
at java.util.ArrayList$Itr.next(ArrayList.java:859)
at Capsule.cleanup0(Capsule.java:1428)
at Capsule.cleanup(Capsule.java:1414)
at Capsule.cleanup1(Capsule.java:1401)
at Capsule.run(Capsule.java:1319)
at java.lang.Thread.run(Thread.java:748)
java.lang.InterruptedException
at java.lang.Object.wait(Native Method)
at java.lang.Object.wait(Object.java:502)
at java.lang.UNIXProcess.waitFor(UNIXProcess.java:395)
at Capsule.launch0(Capsule.java:1382)
at Capsule.launch(Capsule.java:1351)
at Capsule.launch(Capsule.java:1280)
at Capsule.main0(Capsule.java:399)
at Capsule.main(Capsule.java:379)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:678)
Exception in thread "cleanup" java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
at java.util.ArrayList$Itr.next(ArrayList.java:859)
at Capsule.cleanup0(Capsule.java:1428)
at Capsule.cleanup(Capsule.java:1414)
at Capsule.cleanup1(Capsule.java:1401)
at Capsule.run(Capsule.java:1319)
at java.lang.Thread.run(Thread.java:748)
For more detailed output, check the application tracking page: http://content-m:8188/applicationhistory/app/application_1549311784724_0016 Then click on links to logs of each attempt.

```

**Comment by omarzouk** [comment]
Was an unrelated issue, setting a higher timeout on `spark.yarn.am.waitTime` solved the issue.
