### ISSUE TITLE
ArrayIndexOutOfBoundsException upgrading to 0.10.0 version

### ISSUE THREAD

**Issue by pditommaso** [puniverse/capsule#56]
Upgrading from 0.9.0 to 0.10.0 I'm getting the following exception in some environments, though I'm unable to replicate the exact problem.   

    CAPSULE: Dependency manager repositories: [central (https://repo1.maven.org/maven2/, default, releases)]
    CAPSULE: Launching app nextflow-one_0.12.2
    CAPSULE: Locking /users/rg/sdjebali/.nextflow/capsule/apps/nextflow-one_0.12.2/.lock
    CAPSULE: Extracting /nfs/users/rg/sdjebali/.nextflow/framework/0.12.2/nextflow-0.12.2-one.jar to app cache directory /users/rg/sdjebali/.nextflow/capsule/apps/nextflow-one_0.12.2
    CAPSULE: Using JVM: /usr/java/jdk1.7.0_60/jre
    CAPSULE: Unocking /users/rg/sdjebali/.nextflow/capsule/apps/nextflow-one_0.12.2/.lock
    CAPSULE EXCEPTION: 0 while processing attribute Library-Path-A: null
    java.lang.ArrayIndexOutOfBoundsException: 0
        at sun.nio.fs.UnixPath.normalize(UnixPath.java:508)
        at Capsule.toAbsolutePath(Capsule.java:2669)
        at Capsule.processOutgoingPath0(Capsule.java:2609)
        at Capsule.processOutgoingPath(Capsule.java:2603)
        at Capsule.processOutgoingPath(Capsule.java:2617)
        at Capsule.compileClassPath(Capsule.java:1653)
        at Capsule.buildSystemProperties0(Capsule.java:1827)
        at Capsule.buildSystemProperties(Capsule.java:1815)
        at Capsule.buildSystemProperties(Capsule.java:1800)
        at Capsule.buildJavaProcess(Capsule.java:1582)
        at Capsule.buildProcess0(Capsule.java:1153)
        at Capsule.buildProcess(Capsule.java:1144)
        at Capsule.prelaunch0(Capsule.java:1122)
        at Capsule.prelaunch(Capsule.java:1118)
        at CapsuleLoader.prelaunch(CapsuleLoader.java:46)
        at Capsule.prepareForLaunch(Capsule.java:1033)
        at Capsule.launch(Capsule.java:974)
        at Capsule.main0(Capsule.java:296)
        at Capsule.main(Capsule.java:275)

**Comment by pron** [comment]
Closed by [this commit](https://github.com/puniverse/capsule/commit/0341aec0ade3fe73e40306be99666b1bee235deb): work around JDK-8037945
