### ISSUE TITLE
no support for OpenBSD

### ISSUE THREAD

**Issue by pguedes** [puniverse/capsule#63]
Capsule fails with a "unrecognized OS: OpenBSD" when deploying a capsule app to an OpenBSD machine.

I tried getting around this by specifying `-Dos.name=Linux` but then the NIO package hangs trying to get the filesystem implementation which seems to use hardcoded platform specific implementation classes that are not included in the JVM i am trying to use.

```
Exception in thread "main" java.lang.AssertionError: java.lang.ClassNotFoundException: sun/nio/fs/LinuxFileSystemProvider
        at sun.nio.fs.DefaultFileSystemProvider$1.run(DefaultFileSystemProvider.java:49)
        at sun.nio.fs.DefaultFileSystemProvider$1.run(DefaultFileSystemProvider.java:43)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.nio.fs.DefaultFileSystemProvider.createProvider(DefaultFileSystemProvider.java:42)
        at sun.nio.fs.DefaultFileSystemProvider.create(DefaultFileSystemProvider.java:70)
        at java.nio.file.FileSystems$DefaultFileSystemHolder.getDefaultProvider(FileSystems.java:108)
        at java.nio.file.FileSystems$DefaultFileSystemHolder.access$000(FileSystems.java:89)
        at java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(FileSystems.java:98)
        at java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(FileSystems.java:96)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.nio.file.FileSystems$DefaultFileSystemHolder.defaultFileSystem(FileSystems.java:95)
        at java.nio.file.FileSystems$DefaultFileSystemHolder.<clinit>(FileSystems.java:90)
        at java.nio.file.FileSystems.getDefault(FileSystems.java:176)
        at java.nio.file.Paths.get(Paths.java:84)
        at Capsule.<clinit>(Capsule.java:243)
Caused by: java.lang.ClassNotFoundException: sun/nio/fs/LinuxFileSystemProvider
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:266)
        at sun.nio.fs.DefaultFileSystemProvider$1.run(DefaultFileSystemProvider.java:47)
        ... 14 more
```

**Comment by pron** [comment]
Can you provide the stack when you're not setting `-Dos.name=Linux` (which you really shouldn't do...)?
