### ISSUE TITLE
Capsule fails to start on RHEL 6

### ISSUE THREAD

**Issue by rbedia** [puniverse/capsule#72]
I am getting the following error when trying to launch on RHEL 6. Java 7 was installed from the standard Red Hat packages.

```
$ java -Dcapsule.log=verbose -jar demo-capsule-fat.jar 
CAPSULE: Jar: /home/demo/demo-capsule-fat.jar
CAPSULE: Platform: linux
CAPSULE: Initializing app ID
CAPSULE: Initialized app ID: demo-capsule-fat
CAPSULE: Launching app demo-capsule-fat
CAPSULE: Using JVM: /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.79.x86_64/jre
CAPSULE EXCEPTION: Exception while getting attribute JVM-Args while processing system property java.home: /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.79.x86_64/jre
java.lang.RuntimeException: Exception while getting attribute JVM-Args
	at Capsule.getAttribute(Capsule.java:2599)
	at Capsule.buildJVMArgs(Capsule.java:2340)
	at Capsule.buildJVMArgs(Capsule.java:2323)
	at Capsule.buildJavaProcess(Capsule.java:2109)
	at Capsule.buildProcess0(Capsule.java:1451)
	at Capsule.buildProcess(Capsule.java:1442)
	at Capsule.prelaunch0(Capsule.java:1415)
	at Capsule.prelaunch(Capsule.java:1408)
	at Capsule.prepareForLaunch(Capsule.java:1326)
	at Capsule.launch(Capsule.java:1218)
	at Capsule.main0(Capsule.java:373)
	at Capsule.main(Capsule.java:352)
Caused by: java.lang.IllegalStateException: No match found
	at java.util.regex.Matcher.group(Matcher.java:485)
	at Capsule.isJavaDir(Capsule.java:3894)
	at Capsule.getJavaVersion(Capsule.java:3876)
	at Capsule.getAttribute0(Capsule.java:2762)
	at Capsule.attribute00(Capsule.java:2745)
	at Capsule.attribute0(Capsule.java:2537)
	at Capsule.attribute(Capsule.java:2736)
	at Capsule.getAttribute(Capsule.java:2593)
	... 11 more
```

I was able to fix the error by changing the regex on line 3892 from
```
^[^\\-]+-([0-9]+)-
```
to
```
^[^\\-]+-([0-9.]+)-
```
so that it will match the full version number 1.7.0 but I am not sure if this is the correct solution.

**Comment by pron** [comment]
Thanks, I'll take a look.
