### ISSUE TITLE
"File already exists" when unpacking capsule with two deps with same artifact id

### ISSUE THREAD

**Issue by edenman** [puniverse/capsule#76]
I have two dependencies with the same artifact id and same version number but different package names:

```
compile 'com.foo:annotations:MYVERSION`
compile 'com.foo.bar:annotations:MYVERSION`
```
I'm building my capsule using this Gradle task:
```
task fatCapsule(type: FatCapsule) {
  applicationClass 'com.foo.myapp.MyApp'
}
```
This is the stacktrace I get when I try to run the capsule:

```
2015-08-17_18:59:51.66690 java.io.IOException: Exception while extracting jar /data/pods/myapp/myapp/installs/myapp_8c5df4f148a811b604b0d23e41f5cccde6bfbe43/myapp.jar to app cache directory /data/app/myapp/.capsule/apps/com.foo.myapp.MyApp
2015-08-17_18:59:51.66706 	at Capsule.extractCapsule0(Capsule.java:1641)
2015-08-17_18:59:51.66710 	at Capsule.extractCapsule(Capsule.java:1633)
2015-08-17_18:59:51.66713 	at Capsule.buildAppCacheDir0(Capsule.java:1567)
2015-08-17_18:59:51.66717 	at Capsule.buildAppCacheDir(Capsule.java:1549)
2015-08-17_18:59:51.66720 	at Capsule.getAppCache(Capsule.java:1498)
2015-08-17_18:59:51.66723 	at Capsule.buildNativeLibraryPath(Capsule.java:1953)
2015-08-17_18:59:51.66723 	at Capsule.buildSystemProperties(Capsule.java:1908)
2015-08-17_18:59:51.66726 	at Capsule.buildSystemProperties(Capsule.java:1889)
2015-08-17_18:59:51.66729 	at Capsule.buildJavaProcess(Capsule.java:1735)
2015-08-17_18:59:51.66732 	at Capsule.buildProcess0(Capsule.java:1273)
2015-08-17_18:59:51.66736 	at Capsule.buildProcess(Capsule.java:1264)
2015-08-17_18:59:51.66739 	at Capsule.prelaunch0(Capsule.java:1237)
2015-08-17_18:59:51.66742 	at Capsule.prelaunch(Capsule.java:1232)
2015-08-17_18:59:51.66745 	at Capsule.prepareForLaunch(Capsule.java:1146)
2015-08-17_18:59:51.66746 	at Capsule.launch(Capsule.java:1091)
2015-08-17_18:59:51.66749 	at Capsule.main0(Capsule.java:332)
2015-08-17_18:59:51.66752 	at Capsule.main(Capsule.java:311)
2015-08-17_18:59:51.66765 Caused by: java.nio.file.FileAlreadyExistsException: /data/app/myapp/.capsule/apps/com.foo.myapp.MyApp/annotations-MYVERSION.jar
2015-08-17_18:59:51.66769 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
2015-08-17_18:59:51.66772 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
2015-08-17_18:59:51.66775 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
2015-08-17_18:59:51.66778 	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
2015-08-17_18:59:51.66784 	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
2015-08-17_18:59:51.66787 	at java.nio.file.Files.newOutputStream(Files.java:216)
2015-08-17_18:59:51.66790 	at java.nio.file.Files.copy(Files.java:3016)
2015-08-17_18:59:51.66793 	at Capsule.writeFile(Capsule.java:3209)
2015-08-17_18:59:51.66798 	at Capsule.extractJar(Capsule.java:2857)
2015-08-17_18:59:51.66801 	at Capsule.extractCapsule0(Capsule.java:1639)
2015-08-17_18:59:51.66805 	... 16 more
```

**Comment by edenman** [comment]
To me it seems like the filename for jar dependencies should be fully-qualified when it goes into the capsule, so instead of unpacking `annotations-MYVERSION.jar` capsule would be unpacking `com.foo-annotations-MYVERSION.jar` and `com.foo.bar-annotations-MYVERSION.jar`.  Does that sound correct?  Any pointers on where that packing code lives in the capsule-ization code?  Or is this really an issue with the gradle plugin I'm using to generate the capsule ([this](https://github.com/danthegoodman/gradle-capsule-plugin))?

**Comment by danthegoodman** [comment]
@edenman Yeah. It looks like a problem with my plugin. It has to do with how I embed the files at `Capsule.groovy`, line 158. I'll see if I can fix it in the next couple of days.

**Comment by pron** [comment]
Closing the capsule issue.
