### ISSUE TITLE
Exception at the end of capsule execution

### ISSUE THREAD

**Issue by adrienlauer** [puniverse/capsule#90]
When using Capsule 1.0, I encounter an exception at the end of the execution, after my program successfully executed but before its returns to the OS.

        CAPSULE EXCEPTION: Connection reset while processing null null: null
        java.net.SocketException: Connection reset
                at java.net.SocketInputStream.read(Unknown Source)
                at java.net.SocketInputStream.read(Unknown Source)
                at java.net.SocketInputStream.read(Unknown Source)
                at java.io.ObjectInputStream$PeekInputStream.peek(Unknown Source)
                at java.io.ObjectInputStream$BlockDataInputStream.readBlockHeader(Unknown Source)
                at java.io.ObjectInputStream$BlockDataInputStream.refill(Unknown Source)
                at java.io.ObjectInputStream$BlockDataInputStream.read(Unknown Source)
                at java.io.DataInputStream.readInt(Unknown Source)
                at java.io.ObjectInputStream$BlockDataInputStream.readInt(Unknown Source)
                at java.io.ObjectInputStream.readInt(Unknown Source)
                at Capsule.receive(Capsule.java:1782)
                at Capsule.receiveLoop(Capsule.java:1743)
                at Capsule.launch0(Capsule.java:1349)
                at Capsule.launch(Capsule.java:1322)
                at Capsule.launch(Capsule.java:1252)
                at Capsule.main0(Capsule.java:391)
                at Capsule.main(Capsule.java:370)
        CAPSULE: Cleanup
        CAPSULE: Sending message 1 : 1
        CAPSULE: Sending of message 1: 1 failed - Connection reset by peer: socket write error

This doesn't happen when using Capsule 1.0-rc1, as it seems related to the capsule agent feature I noticed:

        CAPSULE: Waiting for client to connect...
        CAPSULE AGENT: Jar: ...\test\target\test-1.0.0-SNAPSHOT-capsule.jar
        CAPSULE AGENT: Platform: windows
        CAPSULE AGENT: Initializing app ID
        CAPSULE AGENT: Initialized app ID: test-1.0.0-SNAPSHOT-capsule.jar
        CAPSULE AGENT: Starting capsule client: 0.0.0.0:65289
        CAPSULE AGENT: Client connected,CAPSULE: Client connected

**Comment by circlespainter** [comment]
Is the exception printed only with `-Dcapsule.log=verbose` or anyway?

**Comment by adrienlauer** [comment]
The detailed exception is only printed with -Dcapsule.log=verbose but the following error message is still displayed without:

    CAPSULE EXCEPTION: Connection reset while processing null null: null (for stack trace, run with -Dcapsule.log=verbose)

**Comment by pron** [comment]
You can try it with the new snapshot (`1.0.1-SNAPSHOT`). I believe this should now be fixed.
